<?php
/**
 * Created by PhpStorm.
 * User: Rémi KOCI
 * Date: 11/04/2015
 * Time: 22:37
 */

class Utilisateur extends Personne {

    private $_utilisateur_prenom;
    private $_utilisateur_adresse;
    private $_utilisateur_cp;
    private $_utilisateur_ville;

    function __construct($id, $pseudo, $nom, $typeuser, $photo, $mail, $tel, $prenom, $adresse, $cp, $ville){
        $this->_utilisateur_prenom = $prenom;
        $this->_utilisateur_adresse = $adresse;
        $this->_utilisateur_cp = $cp;
        $this->_utilisateur_ville = $ville;
        parent::__construct($id, $pseudo, $nom, $typeuser, $photo, $mail, $tel);
    }

    /**
     * @return mixed
     */
    public function getUtilisateurPrenom()
    {
        return $this->_utilisateur_prenom;
    }

    /**
     * @return mixed
     */
    public function getUtilisateurAdresse()
    {
        return $this->_utilisateur_adresse;
    }

    /**
     * @return mixed
     */
    public function getUtilisateurCp()
    {
        return $this->_utilisateur_cp;
    }

    /**
     * @return mixed
     */
    public function getUtilisateurVille()
    {
        return $this->_utilisateur_ville;
    }

    public function getPersonneId()
    {
        return parent::getPersonneId(); // TODO: Change the autogenerated stub
    }

    public function setPersonneId($personne_id)
    {
        parent::setPersonneId($personne_id); // TODO: Change the autogenerated stub
    }

    public function getPersonnePseudo()
    {
        return parent::getPersonnePseudo(); // TODO: Change the autogenerated stub
    }

    public function setPersonnePseudo($personne_pseudo)
    {
        parent::setPersonnePseudo($personne_pseudo); // TODO: Change the autogenerated stub
    }

    public function getPersonneNom()
    {
        return parent::getPersonneNom(); // TODO: Change the autogenerated stub
    }

    public function setPersonneNom($personne_nom)
    {
        parent::setPersonneNom($personne_nom); // TODO: Change the autogenerated stub
    }

    public function getPersonneTypeUser()
    {
        return parent::getPersonneTypeUser(); // TODO: Change the autogenerated stub
    }

    public function setPersonneTypeUser($personne_typeuser)
    {
        parent::setPersonneTypeUser($personne_typeuser); // TODO: Change the autogenerated stub
    }

    public function getPersonnePhoto()
    {
        return parent::getPersonnePhoto(); // TODO: Change the autogenerated stub
    }

    public function setPersonnePhoto($personne_photo)
    {
        parent::setPersonnePhoto($personne_photo); // TODO: Change the autogenerated stub
    }

    public function getPersonneMail()
    {
        return parent::getPersonneMail(); // TODO: Change the autogenerated stub
    }

    public function setPersonneMail($personne_mail)
    {
        parent::setPersonneMail($personne_mail); // TODO: Change the autogenerated stub
    }

    public function getPersonneTel()
    {
        return parent::getPersonneTel(); // TODO: Change the autogenerated stub
    }

    public function setPersonneTel($personne_tel)
    {
        parent::setPersonneTel($personne_tel); // TODO: Change the autogenerated stub
    }
}